function handle_error(error): void
{
    console.log(error);
}